primary_items = {
    "Iron Ingot",
    "Copper Ingot",
    "Caterium Ingot",
    "Concrete",
    "Silica",
    "Raw Quartz",
    "Rubber",
    "Plastic",
    "Aluminum Ingot",
    # "Petroleum Coke",
    "Steel Ingot",
    "Empty Canister",

    "Uranium",
    "Caterium Ore",
    "Copper Ore",
    "Iron Ore",
    "Bauxite",
    "Bacon Agaric",
    "Beryl Nut",
    "Coal",
    "Crude Oil",
    "Excited Photonic Matter",
    "Leaves",
    "Limestone",
    "Mycelia",
    "Nitrogen Gas",
    "Paleberry",
    "Raw Quartz",
    "SAM",
    "Sulfur",
    "Water",
    "Wood",

    # "B0", "B1", "C1", "C2", "D1", "G1", "G2", "F1", "F2",
    # 'D', 'E', 'F', 'G', 'I'
}
primary_items_wiki = set("/wiki/" + i.replace(" ", "_") for i in primary_items)


blacklist_items = {
    "Beacon",
    "Blade Runners",
    "Boom Box",
    "Color Cartridge",
    "Cup",
    "Factory Cart™",
    "FICSIT Coupon",
    "FICSMAS/Equipment",
    "Flower Petals",
    "Fluids",
    "Fuel/zh",
    "Gas Mask",
    "Golden Factory Cart™",
    "Hard Drive",
    "Hazmat Suit",
    "Heavy Oil Residue/zh",
    "Hoverpack",
    "HUB Parts",
    "Jetpack",
    "Medicinal Inhaler",
    "Mercer Sphere",
    "Nobelisk Detonator",
    "Object Scanner",
    "Parachute",
    "Portable Miner",
    "Rebar Gun",
    "Rifle",
    "Somersloop",
    "Statues",
    "User:Ondar111/sandbox",
    "Vines",
    "Xeno-Basher",
    "Xeno-Zapper",
    "Zipline",
    "Hog Remains",
    "Spitter Remains",
    "Stinger Remains",
    "Hatcher Remains",
    "Alien Protein",
    "Alien Remains",
    "Alien DNA Capsule",
    "Blue Power Slug",
    "Yellow Power Slug",
    "Purple Power Slug",
}
blacklist_items_wiki = set("/wiki/" + i.replace(" ", "_") for i in blacklist_items)

blacklist_recipes = {
    "Basic Iron Ingot",
    "Iron Alloy Ingot",
    "Leached Iron ingot",
    "Pure Iron Ingot",
    "Copper Alloy Ingot",
    "Leached Copper Ingot",
    "Pure Copper Ingot",
    "Tempered Copper Ingot",
    "Leached Caterium Ingot",
    "Pure Caterium Ingot",
    "Tempered Caterium Ingot",
    "Distilled Silica",
    "Cheap Silica",
    "Quartz Purification",
    "Fused Quartz Crystal",
    "Pure Quartz Crystal",
    "Turbo Diamonds",

    "Empty Canister",
    "Unpackage Alumina Solution",
    "Unpackage Fuel",
    "Unpackage Heavy Oil Residue",
    "Unpackage Liquid Biofuel",
    "Unpackage Oil",
    "Unpackage Sulfuric Acid",
    "Unpackage Turbofuel",
    "Unpackage Water",
    "Coated Iron Canister",
    "Steel Canister",
    "Unpackage Ionized Fuel",
    "Unpackage Nitric Acid",
    "Unpackage Nitrogen Gas",
    "Unpackage Rocket Fuel",

    "Power Shard (1)",
    "Power Shard (2)",
    "Power Shard (5)"
}
