primary_clean_items = (
    "Iron Ingot",
    "Copper Ingot",
    "Caterium Ingot",
    "Concrete",
    "Silica",
    "Raw Quartz",
    "Rubber",
    "Plastic",
    "Aluminum Ingot",
    # "Petroleum Coke",
    "Empty Canister"
    
    "Caterium Ore",
    "Copper Ore",
    "Iron Ore",
    "Bauxite",
    "Bacon Agaric",
    "Beryl Nut",
    "Coal",
    "Crude Oil",
    "Excited Photonic Matter",
    "Leaves",
    "Limestone",
    "Mycelia",
    "Nitrogen Gas",
    "Paleberry",
    "Raw Quartz",
    "SAM",
    "Sulfur",
    "Water",
    "Wood",
)

primary_items = tuple("/wiki/" + i.replace(" ", "_") for i in primary_clean_items)


blacklist_items = (
    "/wiki/Beacon",
    "/wiki/Blade_Runners",
    "/wiki/Boom_Box",
    "/wiki/Color_Cartridge",
    "/wiki/Cup",
    "/wiki/Factory_Cart™",
    "/wiki/FICSIT_Coupon",
    "/wiki/FICSMAS/Equipment",
    "/wiki/Flower_Petals",
    "/wiki/Fluids",
    "/wiki/Fuel/zh",
    "/wiki/Gas_Mask",
    "/wiki/Golden_Factory_Cart™",
    "/wiki/Hard_Drive",
    "/wiki/Hazmat_Suit",
    "/wiki/Heavy_Oil_Residue/zh",
    "/wiki/Hoverpack",
    "/wiki/HUB_Parts",
    "/wiki/Jetpack",
    "/wiki/Medicinal_Inhaler",
    "/wiki/Mercer_Sphere",
    "/wiki/Nobelisk_Detonator",
    "/wiki/Object_Scanner",
    "/wiki/Parachute",
    "/wiki/Portable_Miner",
    "/wiki/Rebar_Gun",
    "/wiki/Rifle",
    "/wiki/Somersloop",
    "/wiki/Statues",
    "/wiki/User:Ondar111/sandbox",
    "/wiki/Vines",
    "/wiki/Xeno-Basher",
    "/wiki/Xeno-Zapper",
    "/wiki/Zipline",
    "/wiki/Hog_Remains",
    "/wiki/Spitter_Remains",
    "/wiki/Stinger_Remains",
    "/wiki/Hatcher_Remains",
    "/wiki/Alien_Protein",
    "/wiki/Alien_Remains",
    "/wiki/Alien_DNA_Capsule",
    "/wiki/Blue_Power_Slug",
    "/wiki/Yellow_Power_Slug",
    "/wiki/Purple_Power_Slug",
)

blacklist_recipes = (
    "Basic Iron Ingot",
    "Iron Alloy Ingot",
    "Leached Iron ingot",
    "Pure Iron Ingot",
    "Copper Alloy Ingot",
    "Leached Copper Ingot",
    "Pure Copper Ingot",
    "Tempered Copper Ingot",
    "Leached Caterium Ingot",
    "Pure Caterium Ingot",
    "Tempered Caterium Ingot",
    "Distilled Silica",
    "Cheap Silica",
    "Quartz Purification",
    "Fused Quartz Crystal",
    "Pure Quartz Crystal",

    "Empty Canister",
    "Unpackage Alumina Solution",
    "Unpackage Fuel",
    "Unpackage Heavy Oil Residue",
    "Unpackage Liquid Biofuel",
    "Unpackage Oil",
    "Unpackage Sulfuric Acid",
    "Unpackage Turbofuel",
    "Unpackage Water",
    "Coated Iron Canister",
    "Steel Canister",
    "Empty Fluid Tank",
    "Unpackage Ionized Fuel",
    "Unpackage Nitric Acid",
    "Unpackage Nitrogen Gas",
    "Unpackage Rocket Fuel"
)
